### ISSUE TITLE
Pegasus does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Arne-W** [heliorc/pegasus-ui#17]
Hi
I tried to use the pegaus UI 0.1.12 and 0.2.0 on an Ubuntu 18.04 without success. I tried the snap and the Appimage version and they behave exactly the same.

I tried the following:
1st try:
 * Start pegasus -> Connect screen is shown
 * Connect Heliospring with butterflight 3.5.2 
 * Pegaus shows only Cli interface entering commands has no effect

2nd try:
 * connect Heliospring and force into bootloader (with butterflight configurator)
 * Start pegasus -> Shows Firmware selection screen
 * select Heliospring and Raceflight FW (RaceFlightOne_3_041_001_HELIOSPRING.bin)
 * select erase flash and pressed flash button
 * screen changes and starts downloading after few seconds downloading is done
 * after that nothing happens anymore - flashing does not start

3rd try:
 * Start pegasus -> Connect screen is shown
 * Connect Heliospring with already flashed RaceFlightOne_3_041_001_HELIOSPRING.bin
 * Device is detected and an empty screen is shown.

Btw the snap image is only usable when installed with --devmode otherwise appamor denys the com port access.

**Comment by oknowton** [comment]
I had trouble on Ubuntu 18.04 as well.  I tried the snap and the appimage.  I'm doing a bad job.  I don't have error messages handy to paste here.

The dfu fails.  Something is trying to write a temp.bin file to `/snap/pegasus/x2/resources/public/server/utils/dfu`, but it fails because the snap's file system is read only.  I cheated and copied the contents of the snap elsewhere, and I was able to flash 3.6.2 to my quad.

I was not able to update the IMU-F. The reason wasn't obvious. The CLI comes up, there's one line of text about contacting the IMU-F, and it just sits there.  I had to update the IMU-F from my Windows 10 tablet.

Here's where it gets weird.  Before updating the IMU-F, I was often able to configure the quad with the pegasus-ui on Ubuntu.  About half the time, though, it would tell me that it wasn't compatible with the firmware on my quad. Unplugged and replugging the USB cable fixed that most of the time.  This seems to be a problem every time the quad has to be rebooted.

After flashing the IMU-F, the pegasus-ui just shows a blank, gray screen after connecting.

**Comment by orneryd** [comment]
We added steps to the readme for the 0.2.0 release for extracting the appimage, does that work for you?

**Comment by Arne-W** [comment]
Yeah - it works better! I was able to flash RaceFlightOne_3_041_002_HELIOSPRING.bin. But after the reboot pegasus could not connect and emitted this error:
``` (node:5914) UnhandledPromiseRejectionWarning: Error: cannot open device with path /dev/hidraw1
    at new HID (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/node_modules/node-hid/nodehid.js:54:17)
    at Object.getConfig (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/build/server/fcConnector/rf1.js:15:23)
    at FcConnector.getConfig (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/build/server/fcConnector/index.js:196:27)
    at devices.get (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/build/server/express.js:30:12)
    at SerialPort.list (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/build/server/devices/index.js:45:7)
    at promise.then.ports (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/node_modules/@serialport/stream/stream.js:671:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
When using butterflight 3.6.2 it worked much better.
When using BF I was able to flash AND configure the FC using Pegasus. Nevertheless there was this error on the console - but as far as I could see configuring works as expected. 
```creating new port port:  /dev/ttyACM0
Trying to open port:  /dev/ttyACM0
sending command: config on port /dev/ttyACM0
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at sendCommand.then.conf (/home/blaster/Schreibtisch/Pegasus-UI/squashfs-root/resources/app.asar/build/server/fcConnector/bxf.js:64:25)
using open port:  /dev/ttyACM0
sending command: config on port /dev/ttyACM0
```

It would be very cool if there were some additional information on some features - Roll FF (Fast Forward??) and FF transition for example.
